org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m -XX:HeapBaseMinAddress=8g -XX:TieredStopAtLevel=1 -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.daemon=false
org.gradle.parallel=false
org.gradle.workers.max=2
android.useAndroidX=true
android.enableJetifier=true
android.experimental.privately.enableEmptyNamespaceWithDefaultValue=true
android.builder.sdkDownload=true
android.builder.acceptLicenses=true
kotlin.daemon.jvmargs=-Xmx1024m
