org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=768m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.workers.max=4
android.useAndroidX=true
android.enableJetifier=true
android.experimental.privately.enableEmptyNamespaceWithDefaultValue=true
android.builder.sdkDownload=true
android.builder.acceptLicenses=true
android.enableR8=true
kotlin.daemon.jvmargs=-Xmx1536m
